version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///data/app.db"
    volumes:
      - sqlite_data:/app/data
volumes:
  sqlite_data:
