services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///data/app.db"
      SECRET_KEY: "${SECRET_KEY}"
      FRONTEND_ORIGINS: "${FRONTEND_ORIGINS:-http://localhost:8080,http://localhost:5173}"
    volumes:
      - sqlite_data:/app/data
  frontend:
    build:
      context: ./dashboard
      args:
        VITE_API_BASE: http://web:8000
    ports:
      - "8080:80"
    depends_on:
      - web
volumes:
  sqlite_data:
